"""Match Kaggle images to figshare images to recover PATIENT IDs for the Kaggle dataset.

    python -m brainguard.crosswalk     # after `brainguard.audit` and `brainguard.figshare`

Most Kaggle glioma / meningioma / pituitary images are re-encoded figshare slices.
A Kaggle image is matched to the figshare slice with the highest 64x64 pixel
correlation, if that correlation is >= CROSSWALK_CORRELATION. Through the match it
inherits the figshare patient ID, which answers the question the Kaggle split
cannot: how many Kaggle *test* images come from patients who are also in *training*?
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

from . import config
from .audit import thumb64


def thumbs_from_files(root: Path, rel_paths) -> np.ndarray:
    out = []
    for p in rel_paths:
        with Image.open(root / p) as im:
            out.append(thumb64(im))
    return np.stack(out)


def best_matches(a: np.ndarray, b: np.ndarray, chunk: int = 1024) -> tuple[np.ndarray, np.ndarray]:
    """For each row of a, index of the most correlated row of b and that correlation."""
    idx = np.empty(len(a), dtype=int)
    corr = np.empty(len(a))
    for s in range(0, len(a), chunk):
        sim = a[s:s + chunk] @ b.T
        idx[s:s + chunk] = sim.argmax(axis=1)
        corr[s:s + chunk] = sim.max(axis=1)
    return idx, corr


def crosswalk(kaggle: pd.DataFrame, k_thumbs: np.ndarray, fig: pd.DataFrame, f_thumbs: np.ndarray,
              min_corr: float = config.CROSSWALK_CORRELATION) -> pd.DataFrame:
    j, c = best_matches(k_thumbs, f_thumbs)
    out = kaggle.copy()
    out["match_corr"] = c
    matched = c >= min_corr
    out["fig_idx"] = np.where(matched, fig["idx"].to_numpy()[j], -1)
    out["pid"] = np.where(matched, fig["pid"].astype(str).to_numpy()[j], "")
    out["fig_label"] = np.where(matched, fig["label"].to_numpy()[j], "")
    return out


def report(cw: pd.DataFrame) -> dict:
    tum = cw[cw.label != config.NO_TUMOUR]
    m = cw[cw.fig_idx >= 0]
    train_p = set(m.loc[m.split == "train", "pid"])
    test_m = m[m.split == "test"]
    test_overlap = test_m[test_m.pid.isin(train_p)]
    r = {
        "kaggle_tumour_images": int(len(tum)),
        "matched_to_figshare": int(len(m)),
        "matched_share_of_tumour_images": float(len(m) / max(len(tum), 1)),
        "matched_no_tumour_images": int((m.label == config.NO_TUMOUR).sum()),
        "label_agreement_share": float((m.label == m.fig_label).mean()) if len(m) else float("nan"),
        "label_disagreements": int((m.label != m.fig_label).sum()),
        "distinct_figshare_slices_used": int(m.fig_idx.nunique()),
        "kaggle_images_sharing_a_figshare_slice": int(m.fig_idx.duplicated(keep=False).sum()),
        "patients_in_kaggle_train": len(train_p),
        "patients_in_kaggle_test": int(test_m.pid.nunique()),
        "patients_in_both": int(len(train_p & set(test_m.pid))),
        "matched_test_images": int(len(test_m)),
        "test_images_from_training_patients": int(len(test_overlap)),
        "test_images_from_training_patients_share": float(len(test_overlap) / max(len(test_m), 1)),
        "by_class": {lab: {"tumour_images": int((tum.label == lab).sum()),
                           "matched": int((m.label == lab).sum())}
                     for lab in config.TUMOUR_CLASSES},
    }
    return r


def to_markdown(r: dict) -> str:
    L = ["# Kaggle ↔ figshare patient crosswalk (generated by `python -m brainguard.crosswalk`)", "",
         f"Kaggle images matched to a figshare slice (64×64 pixel correlation ≥ {config.CROSSWALK_CORRELATION}): "
         f"**{r['matched_to_figshare']:,} of {r['kaggle_tumour_images']:,} tumour images "
         f"({r['matched_share_of_tumour_images']:.1%})**; no-tumour images matched: {r['matched_no_tumour_images']}.", "",
         "| Class | Kaggle tumour images | Matched to figshare |", "|---|---|---|"]
    L += [f"| {k} | {v['tumour_images']:,} | {v['matched']:,} |" for k, v in r["by_class"].items()]
    L += ["", f"Label agreement between Kaggle folder and figshare label: {r['label_agreement_share']:.1%} "
          f"({r['label_disagreements']} disagreements).",
          f"Distinct figshare slices used: {r['distinct_figshare_slices_used']:,}; Kaggle images that share a slice "
          f"with another Kaggle image: {r['kaggle_images_sharing_a_figshare_slice']:,}.", "",
          "## Patient overlap between Kaggle Training and Testing", "", "| | |", "|---|---|",
          f"| Patients in Training | {r['patients_in_kaggle_train']:,} |",
          f"| Patients in Testing | {r['patients_in_kaggle_test']:,} |",
          f"| **Patients in both** | **{r['patients_in_both']:,}** |",
          f"| **Matched test images from a patient also in Training** | **{r['test_images_from_training_patients']:,} of "
          f"{r['matched_test_images']:,} ({r['test_images_from_training_patients_share']:.1%})** |"]
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kaggle-dir", type=Path, default=config.KAGGLE_DIR)
    ap.add_argument("--figshare-dir", type=Path, default=config.FIGSHARE_DIR)
    ap.add_argument("--artifacts-dir", type=Path, default=config.ARTIFACTS_DIR)
    ap.add_argument("--reports-dir", type=Path, default=config.REPORTS_DIR)
    args = ap.parse_args(argv)
    kaggle = pd.read_csv(args.artifacts_dir / "kaggle_index.csv")
    fig = pd.read_csv(args.figshare_dir / "metadata.csv", dtype={"pid": str})
    kt = thumbs_from_files(args.kaggle_dir, kaggle.path)
    ft = thumbs_from_files(args.figshare_dir, fig.image_path)
    cw = crosswalk(kaggle, kt, fig, ft)
    cw.to_csv(args.artifacts_dir / "kaggle_index.csv", index=False)      # enriched with pid
    r = report(cw)
    (args.reports_dir / "kaggle_crosswalk.json").write_text(json.dumps(r, indent=2))
    (args.reports_dir / "kaggle_crosswalk.md").write_text(to_markdown(r))
    print(to_markdown(r))
    return cw, r


if __name__ == "__main__":
    main()
