"""Shortcut test: can the Kaggle labels be predicted WITHOUT looking at the brain?

    python -m brainguard.shortcut     # after `brainguard.audit`

A gradient-boosted model is trained on file properties only (width, height, aspect
ratio, colour mode, file size, bytes per pixel) on Kaggle Training and scored on
Kaggle Testing. If it scores highly, the labels are confounded with image source,
and any image model's accuracy on this dataset is an upper bound on, not evidence
of, tumour recognition.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import balanced_accuracy_score

from . import config
from .stats import delong_auc, wilson_ci


def metadata_features(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame({
        "width": df.width, "height": df.height, "aspect": df.width / df.height,
        "is_512": ((df.width == 512) & (df.height == 512)).astype(int),
        "mode_L": (df["mode"] == "L").astype(int), "mode_RGB": (df["mode"] == "RGB").astype(int),
        "log_bytes": np.log(df.file_bytes), "bytes_per_pixel": df.file_bytes / (df.width * df.height),
    })


def run(df: pd.DataFrame) -> dict:
    X = metadata_features(df)
    tr, te = (df.split == "train").to_numpy(), (df.split == "test").to_numpy()
    res = {}
    # Binary: tumour vs no tumour
    y = df["is_tumour"].to_numpy()
    m = HistGradientBoostingClassifier(random_state=config.SEED).fit(X[tr], y[tr])
    p = m.predict_proba(X[te])[:, 1]
    pred = (p >= 0.5).astype(int)
    k = int((pred == y[te]).sum())
    res["binary"] = {"auc": delong_auc(y[te], p), "accuracy": k / te.sum(), "accuracy_ci": wilson_ci(k, int(te.sum())),
                     "balanced_accuracy": float(balanced_accuracy_score(y[te], pred))}
    # One rule
    rule = 1 - ((df.width == 512) & (df.height == 512)).astype(int).to_numpy()     # 1 = predict no tumour
    k = int((rule[te] == (1 - y[te])).sum())
    res["rule_not_512_means_no_tumour"] = {"accuracy": k / te.sum(), "accuracy_ci": wilson_ci(k, int(te.sum()))}
    # 4-class
    y4 = df["label"].to_numpy()
    m4 = HistGradientBoostingClassifier(random_state=config.SEED).fit(X[tr], y4[tr])
    pred4 = m4.predict(X[te])
    k = int((pred4 == y4[te]).sum())
    res["four_class"] = {"accuracy": k / te.sum(), "accuracy_ci": wilson_ci(k, int(te.sum())),
                         "balanced_accuracy": float(balanced_accuracy_score(y4[te], pred4)),
                         "chance_accuracy_majority": float(pd.Series(y4[te]).value_counts(normalize=True).iloc[0])}
    res["n_test"] = int(te.sum())
    return res


def to_markdown(r: dict) -> str:
    b, rule, f = r["binary"], r["rule_not_512_means_no_tumour"], r["four_class"]
    ci = lambda c: f"{c[0]:.1%}–{c[1]:.1%}"  # noqa: E731
    return "\n".join([
        "# Shortcut test: labels predicted from file properties only (generated by `python -m brainguard.shortcut`)", "",
        "Model: gradient boosting on width, height, aspect ratio, colour mode, file size and bytes per pixel. "
        f"No pixel values. Trained on Kaggle Training, scored on Kaggle Testing ({r['n_test']:,} images).", "",
        "| Task | Result on Testing |", "|---|---|",
        f"| Tumour vs no tumour | **AUC {b['auc']['auc']:.3f}** (95% CI {b['auc']['ci'][0]:.3f}–{b['auc']['ci'][1]:.3f}) · "
        f"accuracy {b['accuracy']:.1%} ({ci(b['accuracy_ci'])}) · balanced accuracy {b['balanced_accuracy']:.1%} |",
        f"| One rule: \"not 512×512 → no tumour\" | accuracy {rule['accuracy']:.1%} ({ci(rule['accuracy_ci'])}) |",
        f"| 4 classes | accuracy {f['accuracy']:.1%} ({ci(f['accuracy_ci'])}) · balanced accuracy "
        f"{f['balanced_accuracy']:.1%} · majority-class baseline {f['chance_accuracy_majority']:.1%} |",
        "", "Interpretation: the no-tumour class comes from a different source than the tumour classes, so image "
        "geometry and encoding alone separate them. An image model's accuracy on this dataset cannot be read as "
        "evidence that it recognises tumours.", ""])


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--artifacts-dir", type=Path, default=config.ARTIFACTS_DIR)
    ap.add_argument("--reports-dir", type=Path, default=config.REPORTS_DIR)
    args = ap.parse_args(argv)
    df = pd.read_csv(args.artifacts_dir / "kaggle_index.csv")
    r = run(df)
    (args.reports_dir / "kaggle_shortcut.json").write_text(json.dumps(r, indent=2, default=float))
    (args.reports_dir / "kaggle_shortcut.md").write_text(to_markdown(r))
    print(to_markdown(r))
    return r


if __name__ == "__main__":
    main()
